apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-demo
  labels:
    app: secret-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-demo
  template:
    metadata:
      labels:
        app: secret-demo
    spec:
      containers:
      - name: secret-demo
        image: secret-demo:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: hostvol
          mountPath: /etc/foo
      volumes:
      - name: hostvol
        secret:
          secretName: mysecret
          #items:
          #- key: username
           # path: username
          #- key: password
          #  path: password